### PR TITLE
Resolve sub-repository and empty directory

### PR DESCRIPTION
**Pull request by BeoHawk25**
Merge DevOps-Working into branch-dev:

Source code as supplied to the devops team included a copy of the frontend repository, inside the frontend repository. This sub-repo was mitigated by transferring the entire contents of the directory to the root directory of the repository. The then empty directories were then removed, and any file that pointed to or depended on something that had been in the sub-repository was then modified to depend on the altered file locations.

-correcting the sub-repository created in previous iterations 
--move contents of p3-project-registry and delete directory
--delete empty project-registry-frontend directory
--delete duplicate readme and .gitignore
--modify Dockerfile, azure-pipeline.yml to moved resources

-update environments.prod.ts to allow ingress

### CODE REVIEW

**Review by escalonn — CHANGES_REQUESTED** [review]
- the PR title is bad
- the PR description should be corrected, this PR doesn't refactor those files.
- a big-impact PR like this should be done either when no other PRs are active, or, with _careful_ merging afterwards in the other PRs. because this change and every other change to these files is a merge conflict. not the best thing to drop friday afternoon 😁 with PRs like this, exact documentation of every change in the PR description becomes important, because sometimes resolving the conflicts in other PRs (or even in this one) involves replaying those changes manually on those other branches (hence the next point:).
- a PR like this should not mix in other changes like the one to environment.prod.ts, so that it's as easy as possible to handle the merge. changes like that are prone to be erased later in some bad downstream merge that eventually gets back to the integration branch. there's only one thing like that here so we can just keep a close eye out for it and it should be fine.

**Review by dchine — DISMISSED** [review]
Looks to be up to date with dev, including structure improvement & no duplications

- [x] refactor contents of p3-project-registry and delete directory
- [x] delete empty project-registry-frontend directory
- [x] delete duplicate readme and .gitignore

Dockerfile & pipeline are look up to date
environment includes necessary variables
- [x] refactor Dockerfile, azure-pipeline.yml
- [x] update environments.prod.ts to allow ingress

**Comment by BeoHawk25** [comment]
We/I were/was hoping to get Andrews PR merged before this one was merged in to avoid that undoing the work done here. I  see your point about this being a doozey to submit on a Friday afternoon, but I wasn't looking forward to letting this hang over us this weekend.

**Review by escalonn — APPROVED** [review]
the devs know about this PR too, right? if they have work-in-progress they'll have to handle the merge on each of their work-in-progress branches

**Review by escalonn — CHANGES_REQUESTED** [review]
PR build still isn't running properly here.
based on what we see in #3, unfortunately it looks like this move makes sonar think all issues are new again. sonar is usually smarter than that. try getting around this after this PR is merged by affecting the definition of new code so that the issues are once again considered old code. (then our quality gate will make sense).

**Comment by BeoHawk25** [comment]
> the devs know about this PR too, right? if they have work-in-progress they'll have to handle the merge on each of their work-in-progress branches

We have the temporary advantage of not having devs on project yet, so if we can get this merged before they come onboard we can make sure they know of the change, but it shouldn't factor into their work.



> PR build still isn't running properly here.
> based on what we see in #3, unfortunately it looks like this move makes sonar think all issues are new again. sonar is usually smarter than that. try getting around this after this PR is merged by affecting the definition of new code so that the issues are once again considered old code. (then our quality gate will make sense).

The build failures were because a reference that needed to be updated in the pipeline file, corrected and now building. The larger issue is the SonarCloud quality gate. You mention a workaround AFTER the PR is merged? Should we modify the new code definition to get the PR through. or temporarily remove the code analysis check from the branch policy to complete the merge?

**Comment by escalonn** [comment]
> We have the temporary advantage of not having devs on project yet, so if we can get this merged before they come onboard we can make sure they know of the change, but it shouldn't factor into their work.

ah right, duh

> The build failures were because a reference that needed to be updated in the pipeline file, corrected and now building. The larger issue is the SonarCloud quality gate. You mention a workaround AFTER the PR is merged? Should we modify the new code definition to get the PR through. or temporarily remove the code analysis check from the branch policy to complete the merge?

if you handle it after the PR is merged, you can do it with things like incrementing the sonar version number if you think that's the way to want to define the new code. or based on date or something, idk. you can use your admin-override to get this PR through despite failing the quality gate.

**Review by escalonn — APPROVED** [review]
i don't like that the tests are failing in this branch, but because the other PR merged directly from this feature branch, there's now a circular dependency between the PRs. so we'll just have to break the build on dev temporarily in order to get this PR in first. it's not always wrong to merge between feature branches, but it's usually a bad idea cause it leads to this kind of thing. learning opportunity.

**Comment by escalonn** [comment]
let's merge the other PR asap after this one, so that dev doesn't remain broken for long.

**Review by jpbulloch5 — APPROVED** [review]

**Comment by jpbulloch5** [comment]
The failing build is addressed in another PR: https://github.com/1053-August-Duet-Project-Registry/project-registry-frontend/pull/3

**Comment by escalonn** [comment]
go ahead and bypass your branch policies to merge this one; as admin you should be able to merge it anyway depending on the branch policy settings

**Pull request merged**
