### PR TITLE
Fixed models

### PR DESCRIPTION
**Pull request by Kenjilam92**
fixed models in ts

### CODE REVIEW

**Review by gavinmoore2121 — DISMISSED** [review]
breaks everything, but it's necessary. Approved.

**Review by gavinmoore2121 — DISMISSED** [review]
new review after merge conflicts resolved. approved.

**Review by epenn92 — DISMISSED** [review]

**Review by JW406 — APPROVED** [review]
Looks good

**Review by gavinmoore2121 — APPROVED** [review]
good

**Pull request merged**
